import { Component } from '@angular/core';
import {HelloComponent} from './hello/hello.component';

function log(target, name, descriptor) {
  const original = descriptor.value;

  descriptor.value = function (...args) {
    console.log('The arguments passed to the function are', args)
    const result = original.apply(this,args);

    console.log('The result of function is', result)

    return result
  }

}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  constructor() {
    console.log("This statement was generated by constructor",this.aSimpleMethod(5))
  }
  @log
  aSimpleMethod(a) {
    return a*a
  }
}
